name: Release

on:
  push:
    tags:
      - "*"

jobs:
  binaries:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.16"

      - name: Binaries Release
        uses: goreleaser/goreleaser-action@v2.5.0
        with:
          version: ~> 0.159
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
